### ISSUE TITLE
Git 2.36.0 breaks push

### ISSUE THREAD

**Issue by rnd2822** [cristibalan/braid#106]
Hello,
after updating to git 2.36 on my windows machine I get the following errer when trying to push:
```
Braid: Shell error: fatal: Invalid prefix, prefix cannot start with '/'
```
I think I've tracked it down to [operations.rb](https://github.com/cristibalan/braid/blob/master/lib/braid/operations.rb) line 304 where ```read-tree --prefix=/ ...``` is called and the following change within git https://github.com/git-for-windows/git/commit/cc89331ddc92cd89012eaf7937d167b3e0beaecc wich explicitly disallows the prefix parameter to begin with '/'.

**Comment by mattmccutchen** [comment]
Thanks for the report and analysis.  This problem is not specific to Git for Windows: I reproduced it by running the Braid test suite with upstream Git 2.36 on my Linux machine.  The fix looks easy: just use `--prefix=` instead when the path is empty, or it might be safer to drop the `--prefix` option altogether in case the edge case `--prefix=` is rejected in the future.  I'll put together a pull request soon.

**Comment by mattmccutchen** [comment]
Proposed fix in #108.

**Comment by realityforge** [comment]
A fix has been released as version `1.1.6`.

**Comment by mattmccutchen** [comment]
I guess it would be nice if we had a CI job that runs the Braid test suite against a not-yet-released version of Git so we have some early warning of incompatibilities like this and have a chance to fix them before they affect normal users.  I'm not signing up to do the work of setting that up though. :slightly_frowning_face:

**Comment by rnd2822** [comment]
Version ```1.1.6``` working like a charm. Thanks for keeping this great project alive!
