### ISSUE TITLE
Shell error when trying to update one of the braids

### ISSUE THREAD

**Issue by Saragani** [cristibalan/braid#121]
I'm getting: 
Braid: Shell error: From C:/Users/buildmaster/.braid/cache/https___bitbucket.org_some_repo_name

It was working, and the build failed due to a different reason, and then I restarted the build and it failed on this. I tried running it manually, and it fails.
When I build from another branch (the braid json file takes the files from a different branch on the external repo) then it works.

Doing the same thing on my machine, with the same branch that fails on the build machine, works...

I tried restarting the build machine, but it didn't help.
I tried deleting the entire content of the cache directory, and it didn't help.

What should I check?
Thanks

**Comment by mattmccutchen** [comment]
There's probably an underlying error message that we aren't seeing because Braid truncates the stderr of a "shell error" after the first line (see #90).  I'm sorry that #90 has gone unfixed for so long, yet I still can't promise when I'll be able to fix it officially.  If you can run Braid from source and apply [this unofficial patch](https://github.com/cristibalan/braid/compare/master...shell-error-full-quick), then Braid should show the full error message and we can continue the investigation from there.  If patching Braid isn't workable in your environment, I'll see what I can do to get an official fix released soon.

**Comment by Saragani** [comment]
Thanks.

The build machine still has braid 1.1.6, so I will try to update it first (maybe it will solve the issue), and if not, they I will apply the patch
