### ISSUE TITLE
`braid update` can leave repo in an inconsistent state if killed

### ISSUE THREAD

**Issue by mattmccutchen** [cristibalan/braid#35]
I was looking for a subproject management tool that puts the subproject content in the main tree (like `git subtree`) and keeps an explicit record of the upstream commit so it doesn't mess up on revert, merge, and rebase (unlike `git subtree`).  ([Full thread](http://marc.info/?l=git&m=147752326122139&w=2).)  Unfortunately I didn't find out about Braid until after I wrote [my own bare-bones tool](https://mattmccutchen.net/utils/git-subtree-lite.git/), but now I'm looking forward to switching to Braid if I can fix the few important deficiencies compared to my tool.

So, the first thing I saw when reviewing the implementation of `braid update`: it generates temporary commits by actually running a `git commit` command in the user's worktree on the user's branch, so I assume that if it dies in the middle for any reason, it can leave the worktree and branch in an inconsistent state.  Instead, it should use a temporary index file.

If I don't hear any objections, I plan to try to implement this and send a pull request in the next few days.

**Comment by realityforge** [comment]
If I understand what you are saying then I think that may be by design. The reason being that if you have braided in a project and modified it locally and then `braid update` to get remote changes and some of these remote changes conflict with your local changes. How do you manage it? The way braid works now you just manually resolve and commit the changes. If you want a more sophisticated workflow you can always implement this yourself.  I don't understand what your proposed solution would be.

**Comment by mattmccutchen** [comment]
I'm talking about the [temporary commit](https://github.com/cristibalan/braid/blob/7d81da6e86e24de62a74f3ab8d880666cb343b04/lib/braid/commands/update.rb#L98), not the actual merge.  Sorry, I meant to include the link to make this clearer.

**Comment by realityforge** [comment]
Oh - I see. I have never seen this issue crop up but if you think you can protect this scenario then go for it ;)
