### ISSUE TITLE
braid diff no longer pulls the mirror if braided version is not present in cache

### ISSUE THREAD

**Issue by realityforge** [cristibalan/braid#69]
If the version braided into a project is not present in the local cache, braid should synchronize the mirror and try again. Historically it used to always synchronize the mirror so this was never a problem.

**Comment by mattmccutchen** [comment]
Oops, this is a mistake in #62.  The minimal fix to restore the behavior before #62 would be to add the missing `mirror.fetch` call, but due to #71, I propose to check whether the upstream revision is present in the repository before fetching, as you suggest.  This does not address the underlying performance problem, but at least it avoids the problem for repeated `braid diff` calls and doesn't add any complexity that will hurt us later.  We can always implement something better later.

**Comment by realityforge** [comment]
Indeed - that seems like a reasonable approach. I would love to see this one fixed. It bites me ... every now and again ;)
