### ISSUE TITLE
Spaces in command arguments break things

### ISSUE THREAD

**Issue by Devmeon** [cristibalan/braid#88]
Command line:
`braid add --verbose ssh://git@url.git Externe/project`

Output:
```
Braid: Executing `git --version` in D:/folder
Braid: Executing `git rev-parse --is-inside-work-tree` in D:/folder
Braid: Executing `git rev-parse --show-prefix` in D:/folder
Braid: Executing `git status` in D:/folder
Braid: Executing `git rev-parse HEAD` in D:/folder
Braid: Executing `git add .braids.json` in D:/folder
Braid: Adding mirror of 'ssh://git@url.git'.
Braid: Executing `git --version` in D:/folder
Braid: Executing `git rev-parse --is-inside-work-tree` in D:/folder
Braid: Executing `git rev-parse --show-prefix` in D:/folder
Braid: Executing `git config remote.master/braid/Externe/project.url` in D:/folder
Braid: Setup: Creating remote for 'Externe/project'.
Braid: Executing `git remote add master/braid/Externe/project C:/Users/HeadQuarter n°1/.braid/cache/ssh___git_url.git` in D:/folder
Braid: Shell error: usage: git remote add [<options>] <name> <url>
```

braid version : braid 1.1.3
git version : git version 2.27.0.windows.1

**Comment by mattmccutchen** [comment]
Without testing, it looks like the problem is that you have a space in your username and [Braid joins command arguments with spaces and passes the result to the shell without any quoting](https://github.com/cristibalan/braid/blob/4a7eea721fd9c841e305b19ebd6e8c7006c52f53/lib/braid/operations.rb#L102). :frowning_face:  Hopefully we can fix this by moving everything to the forms of `Open3.capture3`, etc. that take a list of arguments.

However, it's generally advisable (even on unix-like OSes) to avoid spaces in file paths for software development work because lots of sloppily written development tools have this kind of bug.  In fact, I think the removal of spaces from a lot of default folder names in Windows Vista (e.g., `Documents and Settings` -> `Users`) was at least partly for this reason, though I haven't confirmed this.

**Comment by Devmeon** [comment]
Your are right, the problem was the space in my username.
After renaming my username, it went smooth as expected.

**Comment by mattmccutchen** [comment]
I'm glad to have confirmation of what the problem was and that you worked around it.  This is still a bug in Braid.

**Comment by mattmccutchen** [comment]
I'm working on getting the `Braid::Operations::Git` class statically typed, which is going to require extensive rework and review of that class and all calls to it anyway, and I'm hoping it will be efficient to fix the problems with spaces at the same time.
