### ISSUE TITLE
JSON schema for .braids.json

### ISSUE THREAD

**Issue by thorsten-klein** [cristibalan/braid#93]
Hello,

it would be great to provide a JSON schema for the .braids.json file.
This could be used by third-party-tools, so that the .braids.json file can be reliably re-used by these tools.

Is there already any JSON schema defined/existing?

Best Regards,
Thorsten

**Comment by mattmccutchen** [comment]
First of all: What third-party tools do you envision accessing .braids.json directly?  We wouldn't want to encourage users to commit to tools that would make it difficult for them to upgrade to newer versions of Braid that change the configuration format.

Assuming we decide it is in fact in the community's best interests to have an official JSON schema for .braids.json: I'm not aware of an existing one; your web search is as good as mine.  It won't be a priority for me to write a schema, but I imagine we would accept a contribution, and it sounds like you might be prepared to write one.  Here's [our informal documentation of the current format](https://github.com/cristibalan/braid/blob/74bde1426c2a2713f8a56a879e5ff2e1e4213ad8/lib/braid/config.rb#L10); I'll be happy to answer questions.  Is there a best practice for where we put the schema in the repository?

**Comment by thorsten-klein** [comment]
Thank you for your fast reply.

I am thinking about any tool which is based on the same information like braid, e.g. as most simple example I think about a python script analyzing the json files and drawing a dependency graph. Therefore it would be helpful to have a well-defined schema for the json file. This helps that the config file will be reused by other open source projects, instead of creating a new file with almost equal content, and as a result maybe a new standard is agreed. Of course the schema could/should then also be used by braid as a check to ensure an always valid json file. 

I am compeletly new to ruby, so the implementation I am most likely not able to do. I try to have a look on the schema at the weekend and contribute. I will also check for best practices regarding the location.

**Comment by mattmccutchen** [comment]
Drawing a dependency graph sounds reasonable.  I don't think there's much chance of convincing Braid and other dependency management tools to adopt a common format for their primary configuration since they all have different feature sets: that's why they are different tools in the first place.  Extracting data from the primary configuration into a common format for analysis would be more realistic.

To write a schema, you wouldn't have to write any Ruby.  At most you might need to read a little Ruby in order to understand what Braid is doing.  But the format is pretty straightforward and I suspect you can translate the comment I linked above to a JSON schema without much difficulty.
